const strings = {
  LOG_IN: 'Log in',
  ACCEPT_TERMS: 'By signing in I accept the',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FORRGOT_PASSWORD: 'Forgot my password',
  ERROR_MESSAGE: 'Email or password is not correct',
  GENERAL_ERROR: 'Something went wrong!',
  FOR_ACCOUNT: '(for your user account)',
  FROM_EMAIL: '(from email)',
  SEND: 'SEND',
  MIN_6DIGITS: '6 digit code',
  MIN_6CHAR: '(min 6 characters)',
  NEW_PASSWORD: 'New Password',
  CODE_ERROR: 'Code is not correct',
  UPDATE: 'UPDATE',
  LOGOUT: 'LOGOUT',
  BY_SIGNING_IN: 'By signing in I accept the',
  GENERAL_TERMS: 'General Terms',
  RESET_PASS: 'Reset Password',
  FORGOT_PASS: 'Forgot Password',
  MAIN_SCREEN: 'Main Screen',
};

export default strings;
